name: Deploy to GitHub Pages

on:
  push:
    branches: [gh-pages]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: |
          cd frontend-riformula
          npm ci

      - name: Build frontend
        run: |
          cd frontend-riformula
          npm run build

      - name: Create .env file with API token
        env:
          OPENROUTER_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          cd Deep-AI
          echo "OPENROUTER_API_KEY=${OPENROUTER_KEY}" > .env

      - name: Install backend dependencies
        run: |
          cd Deep-AI
          npm ci

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Prepare deployment files
        run: |
          mkdir -p dist
          cp -r frontend-riformula/dist/* dist/
          mkdir -p dist/api
          cp Deep-AI/riformulaDescrizione.js dist/api/
          cp Deep-AI/.env dist/api/
          echo "<html><body>API endpoint</body></html>" > dist/api/index.html
          echo "Contenuto della cartella dist:"
          ls -la dist/

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
